# Generated by Django 5.0.7 on 2024-07-25 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avance_materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Catedratico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_identidad', models.CharField(max_length=50, unique=True)),
                ('paterno', models.CharField(max_length=50)),
                ('materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('activo', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.CharField(max_length=10)),
                ('contenido', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=200)),
                ('codigo_materia', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Avance_tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultades', models.CharField(max_length=500)),
                ('sugerencias', models.CharField(max_length=500)),
                ('avance_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repotesemanal.avance_materia')),
            ],
        ),
        migrations.CreateModel(
            name='Avance_contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avance_tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repotesemanal.avance_tema')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repotesemanal.contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paralelo', models.CharField(max_length=10)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repotesemanal.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Catedratico_materia_paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catedratico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repotesemanal.catedratico')),
                ('paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repotesemanal.paralelo')),
            ],
        ),
        migrations.AddField(
            model_name='avance_materia',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repotesemanal.paralelo'),
        ),
        migrations.CreateModel(
            name='Reporte_semanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('nro_semana', models.IntegerField()),
                ('catedratico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repotesemanal.catedratico')),
            ],
        ),
        migrations.AddField(
            model_name='avance_materia',
            name='reporte_semanal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repotesemanal.reporte_semanal'),
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.CharField(max_length=10)),
                ('tema', models.CharField(max_length=500)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repotesemanal.materia')),
            ],
        ),
        migrations.AddField(
            model_name='contenido',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repotesemanal.tema'),
        ),
        migrations.AddField(
            model_name='avance_tema',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repotesemanal.tema'),
        ),
    ]
